<?xml version="1.0" encoding="utf-8"?>
<Project>
    <PropertyGroup>
        <BaseOutputPath>$(MSBuildThisFileDirectory)bin\</BaseOutputPath>
        <BaseIntermediateOutputPath>$(MSBuildThisFileDirectory)obj\$(MSBuildProjectName)\</BaseIntermediateOutputPath>
    </PropertyGroup>

    <PropertyGroup>
        <CheckEolWorkloads>false</CheckEolWorkloads>
    </PropertyGroup>
</Project>
