// This file was auto-generated by ML.NET Model Builder.
using Microsoft.ML;
using Microsoft.ML.Data;
using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
namespace TitanicSurvivalRegression
{
    public partial class TitanicModel
    {
        /// <summary>
        /// model input class for TitanicModel.
        /// </summary>
        #region model input class
        public class ModelInput
        {
            [ColumnName(@"PassengerId")]
            public float PassengerId { get; set; }

            [ColumnName(@"Survived")]
            public float Survived { get; set; }

            [ColumnName(@"Pclass")]
            public float Pclass { get; set; }

            [ColumnName(@"Name")]
            public string Name { get; set; }

            [ColumnName(@"Gender")]
            public string Gender { get; set; }

            [ColumnName(@"Age")]
            public float Age { get; set; }

            [ColumnName(@"SibSp")]
            public float SibSp { get; set; }

            [ColumnName(@"Parch")]
            public float Parch { get; set; }

            [ColumnName(@"Ticket")]
            public float Ticket { get; set; }

            [ColumnName(@"Fare")]
            public float Fare { get; set; }

            [ColumnName(@"Cabin")]
            public float Cabin { get; set; }

            [ColumnName(@"Embarked")]
            public string Embarked { get; set; }

        }

        #endregion

        /// <summary>
        /// model output class for TitanicModel.
        /// </summary>
        #region model output class
        public class ModelOutput
        {
            [ColumnName(@"PassengerId")]
            public float PassengerId { get; set; }

            [ColumnName(@"Survived")]
            public float Survived { get; set; }

            [ColumnName(@"Pclass")]
            public float Pclass { get; set; }

            [ColumnName(@"Name")]
            public string Name { get; set; }

            [ColumnName(@"Gender")]
            public float[] Gender { get; set; }

            [ColumnName(@"Age")]
            public float Age { get; set; }

            [ColumnName(@"SibSp")]
            public float SibSp { get; set; }

            [ColumnName(@"Parch")]
            public float Parch { get; set; }

            [ColumnName(@"Ticket")]
            public float Ticket { get; set; }

            [ColumnName(@"Fare")]
            public float Fare { get; set; }

            [ColumnName(@"Cabin")]
            public float Cabin { get; set; }

            [ColumnName(@"Embarked")]
            public float[] Embarked { get; set; }

            [ColumnName(@"Features")]
            public float[] Features { get; set; }

            [ColumnName(@"Score")]
            public float Score { get; set; }

        }

        #endregion

        private static string MLNetModelPath = Path.GetFullPath("TitanicModel.zip");

        public static readonly Lazy<PredictionEngine<ModelInput, ModelOutput>> PredictEngine = new Lazy<PredictionEngine<ModelInput, ModelOutput>>(() => CreatePredictEngine(), true);

        /// <summary>
        /// Use this method to predict on <see cref="ModelInput"/>.
        /// </summary>
        /// <param name="input">model input.</param>
        /// <returns><seealso cref=" ModelOutput"/></returns>
        public static ModelOutput Predict(ModelInput input)
        {
            var predEngine = PredictEngine.Value;
            return predEngine.Predict(input);
        }

        private static PredictionEngine<ModelInput, ModelOutput> CreatePredictEngine()
        {
            var mlContext = new MLContext();
            ITransformer mlModel = mlContext.Model.Load(MLNetModelPath, out var _);
            return mlContext.Model.CreatePredictionEngine<ModelInput, ModelOutput>(mlModel);
        }
    }
}
