apply plugin: 'java'
apply plugin: 'application'

group = 'org.example'

mainClassName = "org.example.Main"

dependencies {
    implementation project(':src:common')

    testImplementation 'org.junit.jupiter:junit-jupiter-api:5.10.0'
    testImplementation 'org.junit.jupiter:junit-jupiter-params:5.10.0'
    testRuntimeOnly 'org.junit.jupiter:junit-jupiter-engine:5.10.0'
}

test {
    useJUnitPlatform()
}
